# Generated by Django 2.2.7 on 2020-08-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmptyCharacterSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('slug', models.SlugField()),
                ('bio', models.TextField(blank=True, max_length=300, null=True)),
                ('hp', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
