# Generated by Django 2.2.7 on 2020-09-16 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSheetTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oneshot', models.CharField(max_length=120)),
                ('oneshoturl', models.URLField(blank=True, max_length=300, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmptyCharacterSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=300, null=True)),
                ('hp', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateFeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featName', models.CharField(blank=True, max_length=120)),
                ('featVal', models.CharField(blank=True, max_length=120)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templatefeat', to='sheets.CharacterSheetTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Feat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featName', models.CharField(blank=True, max_length=120)),
                ('featVal', models.CharField(blank=True, max_length=120)),
                ('characterSheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charactersheetfeat', to='sheets.EmptyCharacterSheet')),
            ],
        ),
    ]
