# Generated by Django 2.2.7 on 2020-08-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emptycharactersheet',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
