# Generated by Django 2.2.7 on 2020-09-07 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_emptycharactersheet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featName', models.CharField(blank=True, max_length=120)),
                ('featVal', models.CharField(blank=True, max_length=120)),
                ('characterSheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charactersheetfeat', to='sheets.EmptyCharacterSheet')),
            ],
        ),
    ]
