# Generated by Django 2.2.7 on 2020-09-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
